name = "mailfree"
# name = "mail-exhibit"
main = "src/server.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "TEMP_MAIL_DB"
database_name = "xzcxz" #你的d1数据库名称
database_id = "fcfc725c-2a65-4e4c-a320-4581d4d0dd59" # 你的database_id

# 环境变量
[vars]
ADMIN_NAME="iding"
ADMIN_PASSWORD="asdfgh"
GUEST_PASSWORD="admisdsdan"
JWT_TOKEN="fjiwaiv23164s4f6df6wfdx"
JWT_TOKENGUEST_PASSWORD="fzsjfizw874984esfu8df7sr3"
# FORWARD_RULES="[{"prefix":"vip","email":"a@example.com"},{"prefix":"*","email":"2141083706@qq.com"}]"
MAIL_DOMAIN="idinging.com,iding.me,dding.asia,iding.asia,dinging.top,izhou.netlib.re,xiaomajie.asia,iding.qzz.io,12138.qzz.io,iding.cloudns.ch,iding.x10.mx,iding.elementfx.com,iding.x10host.com,izhou.x10.mx,952405.dpdns.org,"
RESEND_API_KEY="dinging.top=re_ahF44aPK_2SERJuTLxcN8t86ChXXYpcBY,iding.qzz.io=re_J2fKFbBW_2xYbv8cnDLpqnRtcx5FDHBuh,iding.asia=re_3KH4SQ6M_KkSSbvAvx9QCYCMGGXzqUWHK"



# 静态资源目录（Workers + Assets）
[assets]
directory = "public"
# 显式指定绑定名，确保在 Worker 中通过 env.ASSETS 可用
binding = "ASSETS"


# R2 存储桶绑定（用于保存完整 EML 内容）
[[r2_buckets]]
binding = "MAIL_EML"
bucket_name = "mail-eml"

# wrangler.toml (wrangler v3.88.0^) 日志服务
# [observability.logs]
# enabled = true



